---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-sample
  labels:
    app: web
spec:
  containers:
    - name: sample-httpd
      image: gcr.io/identity-pingfed-lab-ef24f2/sample-httpd:v1.0.6
      ports:
        - containerPort: 80
